pub mod alerts;
pub mod audit_logs;
pub mod blocklist;
pub mod dashboard;
pub mod devices;
pub mod login;
pub mod rules;
pub mod settings;
pub mod traffic;

pub use alerts::AlertsPage;
pub use audit_logs::AuditLogsPage;
pub use blocklist::BlocklistPage;
pub use dashboard::DashboardPage;
pub use devices::DevicesPage;
pub use login::LoginPage;
pub use rules::RulesPage;
pub use settings::SettingsPage;
pub use traffic::TrafficPage;
